---
- name: Install Tomcat server
  hosts: localhost
  become: true

  vars:
    tomcat_version: 10.1.46
    tomcat_major: 10
    download_url: "https://dlcdn.apache.org/tomcat/tomcat-{{ tomcat_major }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
    download_dest: "/usr/local/apache-tomcat-{{ tomcat_version }}.tar.gz"
    install_dir: "/opt"
    tomcat_home: "/opt/apache-tomcat-{{ tomcat_version }}"

  tasks:
    - name: Install Java
      ansible.builtin.yum:
        name: java
        state: latest

    - name: Download Tomcat
      ansible.builtin.get_url:
        url: "{{ download_url }}"
        dest: "{{ download_dest }}"

    - name: Extract Tomcat package
      ansible.builtin.unarchive:
        src: "{{ download_dest }}"
        dest: "{{ install_dir }}"
        remote_src: yes

    - name: Start Tomcat service
      ansible.builtin.shell: "{{ tomcat_home }}/bin/startup.sh"
      args:
        chdir: "{{ tomcat_home }}/bin"
